**01 – Schema Exploration: Bluesky Blocking Data**

Understand the structure, meaning, and quality of each Parquet file before analysis. This notebook focuses on:

- Column names & data types
- Primary keys & foreign keys
- Timestamps & user identifiers
- Missing values & duplicates
- Early hypotheses about relationships between tables

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
blocks = pd.read_parquet("blocks.parquet")
list_blocks = pd.read_parquet("list_blocks.parquet")
lists = pd.read_parquet("lists.parquet")
list_items = pd.read_parquet("list_items.parquet")


posts = pd.read_parquet("chunk_0_posts.parquet")
likes = pd.read_parquet("chunk_0_likes.parquet")
reposts = pd.read_parquet("chunk_0_reposts.parquet")
follows = pd.read_parquet("chunk_0_follow.parquet")

In [10]:
def schema_overview(df, name):
    print(f"\n=== {name} ===")
    display(df.head())
    display(df.dtypes)
    print("Rows:", len(df))
    display(df.isna().mean().sort_values(ascending=False))

In [11]:
schema_overview(blocks, "blocks")

=== blocks ===

   did_id created_date  subject_did_id
0      57   2024-11-22        23915104
1      57   2024-11-22          895451
2      57   2024-11-23        29069417
3      57   2024-11-23        15995488
4      57   2024-11-23        17542092

did_id             int64
created_date      object
subject_did_id     int64
dtype: object

Rows: 78287665

did_id            0.0
created_date      0.0
subject_did_id    0.0
dtype: float64

In [12]:
schema_overview(list_blocks, "list_blocks")

=== list_blocks ===

   did_id created_date  subject_did_id   subject_collection
0  980589   2024-11-11        21917588  app.bsky.graph.list
1  980589   2024-11-16         6364923  app.bsky.graph.list
2  980589   2024-11-17         2585766  app.bsky.graph.list
3  980589   2024-11-18         2546345  app.bsky.graph.list
4  980589   2024-11-18         8447881  app.bsky.graph.list

did_id                 int64
created_date          object
subject_did_id         int64
subject_collection    object
dtype: object

Rows: 2242503

did_id                0.0
created_date          0.0
subject_did_id        0.0
subject_collection    0.0
dtype: float64

In [13]:
schema_overview(lists, "lists")

=== lists ===

,did_id,created_date,purpose,name,labels
0,12891240,2025-03-18,app.bsky.graph.defs#curatelist,Lovely Morning People,None
1,12891240,2025-03-18,app.bsky.graph.defs#curatelist,Wulferhampton People,None
2,12891240,2025-03-18,app.bsky.graph.defs#curatelist,Lovely Random People,None
3,12891240,2025-03-18,app.bsky.graph.defs#curatelist,Satire,None
4,12891240,2025-04-10,app.bsky.graph.defs#curatelist,UK Politics,None

did_id           int64
created_date    object
purpose         object
name            object
labels          object
dtype: object

Rows: 333460

labels          0.999994
did_id          0.000000
created_date    0.000000
purpose         0.000000
name            0.000000
dtype: float64

In [14]:
schema_overview(list_items, "list_items")

=== list_items ===

   did_id created_date  subject_did_id  list_did_id      list_collection
0  246360   2025-04-06        16547386       246360  app.bsky.graph.list
1  246360   2025-04-06        14431541       246360  app.bsky.graph.list
2  246360   2025-04-06        21573712       246360  app.bsky.graph.list
3  246360   2025-04-06        10912287       246360  app.bsky.graph.list
4  246360   2025-04-06        19906577       246360  app.bsky.graph.list

did_id              int64
created_date       object
subject_did_id      int64
list_did_id         int64
list_collection    object
dtype: object

Rows: 22165395

did_id             0.0
created_date       0.0
subject_did_id     0.0
list_did_id        0.0
list_collection    0.0
dtype: float64

In [15]:
schema_overview(posts, "posts")

=== posts ===

     did_id                       created_at languages labels
0   6484551 2025-03-12 11:10:14.248000+00:00    ["pt"]   None
1  14620149 2025-01-30 03:23:04.576000+00:00    ["en"]   None
2  13619634 2025-01-03 21:12:59.574000+00:00    ["en"]   None
3  13619634 2025-01-27 17:28:16.627000+00:00    ["en"]   None
4  13619634 2025-01-29 02:25:00.875000+00:00    ["en"]   None

did_id                      int64
created_at    datetime64[us, UTC]
languages                  object
labels                     object
dtype: object

Rows: 1890998

labels        0.999396
did_id        0.000000
created_at    0.000000
languages     0.000000
dtype: float64

In [16]:
schema_overview(likes, "likes")

=== likes ===

,did_id,created_at,subject
0,3,2025-01-01 15:39:57.932000+00:00,"{'did_id': 10793535, 'collection': 'app.bsky.f..."
1,3,2025-01-01 15:55:34.229000+00:00,"{'did_id': 10793535, 'collection': 'app.bsky.f..."
2,3,2025-01-04 17:59:01.782000+00:00,"{'did_id': 22738738, 'collection': 'app.bsky.f..."
3,3,2025-01-06 21:04:36.466000+00:00,"{'did_id': 10793535, 'collection': 'app.bsky.f..."
4,3,2025-01-10 06:58:22.678000+00:00,"{'did_id': 25272785, 'collection': 'app.bsky.f..."

did_id                      int64
created_at    datetime64[us, UTC]
subject                    object
dtype: object

Rows: 8713185

did_id        0.0
created_at    0.0
subject       0.0
dtype: float64

In [17]:
schema_overview(follows, "follows")

=== follows ===

   did_id                       created_at  subject_id
0       1 2025-01-03 08:26:18.897000+00:00     2607739
1       1 2025-01-07 06:47:53.250000+00:00    19674894
2       2 2025-01-01 13:24:31.473000+00:00     1345260
3       2 2025-01-01 13:24:48.016000+00:00    29880765
4       3 2025-01-04 11:26:07.454000+00:00     8900182

did_id                      int64
created_at    datetime64[us, UTC]
subject_id                  int64
dtype: object

Rows: 1536586

did_id        0.0
created_at    0.0
subject_id    0.0
dtype: float64

In [18]:
set(blocks.columns) & set(posts.columns)

{'did_id'}